### ISSUE TITLE
Error op Windows

### ISSUE THREAD

**Issue by apollo-inspire** [antwanvdm/php7-vagrant#1]
Op Windows (Windows 10 Home, 21H2,19044.1526) krijg ik deze error wanneer ik na het correct volgen van de installatie `vagrant up` uitvoer 

<img width="1097" alt="2022-03-07 14_17_47-Freddie Sunshine - Tabs" src="https://user-images.githubusercontent.com/22814062/157042045-5997c464-0dd2-4b3b-850c-97a5b2728eac.png">
(ik zit in een admin powershell)

`.vagrantuser`
```
project:
    name: "php-vagrant"
    local_git_path: "C:/coding/php-vagrant"
    provider: "virtualbox"
    ip_address: 192.168.50.5
    vagrant_max_memory: 2048
```
